### ISSUE TITLE
cant login

### ISSUE THREAD

**Issue by TophC7** [marcsello/bme-branded-login#2]
everything seems to work fine but after inputting my username and password it just keeps giving me an error

**Comment by ghost** [comment]
Can you clarify what you mean by error?

**Comment by TophC7** [comment]
Just the a red bar and doesn't login after hitting enter

No actual error message or anything sorry 😅

**Comment by ghost** [comment]
I don't mean to sound condensing, but are you sure your username/password is correct?

Press ctrl+alt+F2 and try logging in there to make sure.

**Comment by marcsello** [comment]
Can you please try changing your username/password to something simple with ASCII characters only? I'm not sure if unicode characters handled properly.

**Comment by TophC7** [comment]
Yes i am sure my username and password are correct

and @marcsello what do you mean by ascii characters only?? im assuming my user name 'chris'  and my password of just letters and numbers is not very complicated

**Comment by marcsello** [comment]
Have you tried other themes as well?
If you are certain that others work, can you please mention some that you tried, and works well, so I can check what could be the difference.
Also can you please tell the lightdm and the webkit2-greeter version and the distro you are using?

**Comment by TophC7** [comment]
Well I'm currently running Solus and installed [web-greeter](https://github.com/Antergos/web-greeter) form source. I should have mentioned this before sorry

As for themes that are working so far only the default one (antergos) seems to work, sort of. All the ones I've tried seem to not work with varying degrees of functionality. I thought yours would work since it required me to input my username manually but nope. Im postivive the web-greeter is at fault here to some extent but I dont know how much

edit: 
lightdm version: 1.28.0
web-greeter: from source 2 days ago???

**Comment by TophC7** [comment]
I'ts working! I just had to install an older version. Thanks!
